services:
  inventory-db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - 5174:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data